name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: zh
          SHOW_TITLE: false
          SECTION_NAME: waka
          SHOW_TIME: false
          SHOW_TOTAL: false
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: false
          SHOW_LANGUAGES: false # 隐藏最常使用的语言
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_PROJECTS: false # 隐藏项目数据（GitHub相关）
          SHOW_BRANCHES: false # 隐藏分支数据（GitHub相关）
          SYMBOL_VERSION: "2" # 设置为进度条的符
          SHOW_SHORT_INFO: "False" # 用户的简短趣闻信息

